# Various types of symmetry for discrete groups 

## The Main Result {#flocinor}

Throughout this thesis, $\textsf{G}$ will be a discrete group with unit $\textsf{e}$.
As explained in Remark \@ref(cnj:lantors), there is no loss if we assume it amenable. For
constructions involving graded $C^*$-algebras we followed [@Ex3; @FD2] ;
we decided not to mention Fell bundles explicitly (with one exception),
but they can be perceived in the background.

::: {.definition #claro} 
We say that the unital $C^*$-algebra
$\mathfrak{C}$ is $\textsf{G}$*-graded* if that there is a family
$\big\{\mathfrak{C}_g\,\vert\,g\in{\textsf{G}}\big\}$ of closed
subspaces of $\mathfrak{C}$ such that the algebraic direct sum
$\,\bigoplus_{g\in{\textsf{G}}}\mathfrak{C_g}$ is dense in
$\mathfrak{C}$ and such that

1.  $\mathfrak{C}_g\mathfrak{C}_h\subset\mathfrak{C}_{gh}\,$ for every
    $g,h\in{\textsf{G}}$ ,

2.  $\mathfrak{C}_g^*\subset\mathfrak{C}_{g^{-1}}\,$ for every
    $g\in{\textsf{G}}$ ,

For every $h\in{\textsf{G}}$ we denote by
$P_h:\bigoplus_{g\in{\textsf{G}}}\!\mathfrak{C}_g\to\mathfrak{C}_h$
the canonical projection (in general it might not be continuous). If
$P_\textsf{e}$ is continuous, $\mathfrak{C}$ is *a topologically
${\textsf{G}}$-graded $C^*$-algebra.* We are going to write
\begin{equation}
\mathfrak{C}=\widetilde{\bigoplus}_{g\in{\textsf{G}}}\mathfrak{C}_g\,. (\#eq:veverita)
\end{equation}
:::

For $\Phi,\Psi\in\bigoplus_{g\in\textsf{G}}\mathfrak{C}_g$ and $g\in\textsf{G}$ one
verifies easily that 
\begin{equation} 
P_g(\Phi\Psi)=\sum_{hk=g}P_h(\Phi)P_k(\Psi)\,(\#eq:multiplix)
\end{equation}
\begin{equation}
P_g(\Phi)^*=P_{g^{-1}}(\Phi^*)\,.(\#eq:multiplex)
\end{equation} 
 When the grading is topological,
there are several facilities which will be crucial for our approach. Let
us denote by $\widetilde{P}_\textsf{e}:\mathfrak{C}\to\mathfrak{C_\textsf{e}}$ the
extension of $P_\textsf{e}$ to a linear bounded map. By Tomiyama's Theorem ([@BO
Thm. 1.5.10], see also [@Ex3 Thm. 3.3]), it is a positive contractive
conditional expectation. Then all the projections $P_g$ do extend to
contractions $\widetilde{P}_g:\mathfrak{C}\to\mathfrak{C_g}$ . We refer
to the proof of Theorem \@ref(thm:teoremix),(ii) for another use of topological grading, in
conjunction with amenability.

::: {.definition #glaro} Let $\mathfrak{C}$ be a topologically graded
$C^*$-algebra. On $\,\bigoplus_{g\in{\textsf{G}}}\!\mathfrak{C}_g$ we
can introduce the new norm
$$\,\big\Vert\,\!\Phi\!\,\big\Vert\,_{\ell^1(\mathfrak C)}\,:=\sum_{g\in{\textsf{G}}}\,\big\Vert\,\! P_g(\Phi)\!\,\big\Vert\,.$$
The completion $\ell^1(\mathfrak{C})$ of
$\bigoplus_{g\in {\textsf{G}}}\!\mathfrak{C}_g$ in this norm is
called *the $\ell^1$-algebra of the graded $C^*$-algebra
$\mathfrak{C}$*.
:::

Since $\Vert\!\cdot\!\Vert\,\le\,\Vert\!\cdot\!\Vert_{\ell^1(\mathfrak{C})}$ on
$\bigoplus_{g\in\textsf{G}}\!\mathfrak{C}_g$, one may interpret
$\ell^1(\mathfrak{C})$ as a subspace of $\mathfrak{C}$:
$$\label{interpretatix}
\ell^1(\mathfrak{C})=\Big\{\Phi\in\mathfrak{C}\;\Big\vert\,\sum_{g\in\textsf{G}}\,\big\Vert\,\! \widetilde{P}_g(\Phi)\!\,\big\Vert\,\,<\infty\Big\}\,.$$
In fact it is a Banach $^*$-subalgebra with the algebraic structure
borrowed from $\mathfrak{C}$ and its new norm. Its elements may be
written as unconditionally convergent series
$\Phi=\sum_{g\in\textsf{G}}\widetilde{P}_g(\Phi)$ in the norm topology.

The next result, besides being interesting in itself, is basic for our
approach.

::: {.proposition #isometrix}
Let $\mathfrak{C}=\widetilde{\bigoplus}_{g\in{\textsf{G}}}\mathfrak{C}_g$
be a topologically graded $C^*$-algebra over a discrete group
[${\textsf{G}}$]{.roman}. There exists a $C^*$-algebra $\mathcal{B}$ and an
isometric $^*$-morphism $$\label{guyana}
T:\ell^1(\mathfrak{C})\hookrightarrow \ell^1({\textsf{G}};\mathcal{B})\equiv\ell^1({\textsf{G}})\otimes \mathcal{B}\,.$$
:::

::: proof
Let $\pi:\mathfrak{C}\to\mathbb{B}(\mathcal{H})$ be a faithful
representation. For any $g\in\textsf{G}$ we denote by $\pi_g$ the restriction of
$\pi$ to the closed subspace $\mathfrak{C}_g$; it is a linear isometry.
One has $$\label{primika}
\pi_g(\Phi)\pi_h(\Psi)=\pi_{gh}(\Phi\Psi)\,,\quad\forall\,g,h\in\textsf{G}\,,\ \Phi\in\mathfrak{C}_g\,,\ \Psi\in\mathfrak{C}_h\,,$$
$$\label{secundika}
\pi_g(\Phi^*)=\pi_{g^{-1}}(\Phi)^*,\quad\forall\,g\in\textsf{G}\,,\ \Phi\in\mathfrak{C}_g\,.$$

Then we set $$\label{tronc}
\big[T(\Phi)\big](g):=\pi_g\big[\widetilde P_g(\Phi)\big]\,,\quad\Phi\in\ell^1(\mathfrak{C})\,,\ g\in\textsf{G}\,.$$
Clearly $T$ is a well-defined linear isometry from $\ell^1(\mathfrak C)$
to $\ell^1\big(\textsf{G},\mathbb B(\mathcal{H})\big)$ :
$$\,\big\Vert\,\!T(\Phi)\!\,\big\Vert\,_{\ell^1(\textsf{G},\mathbb B(\mathcal{H}))}\,=\sum_{g\in\textsf{G}}\,\big\Vert\,\!\pi_g\big[\widetilde P_g(\Phi)\big]\!\,\big\Vert\,_{\mathbb B(\mathcal{H})}\,=\sum_{g\in\textsf{G}}\,\big\Vert\,\!\widetilde P_g(\Phi)\!\,\big\Vert\,\,=\,\,\big\Vert\,\!\Phi\!\,\big\Vert\,_{\ell^1(\mathfrak C)}.$$
To check that $T$ respects the algebraic operations, it is enough to
work with elements of the algebraic direct sum. By taking
$\Phi,\Psi\in\bigoplus_g\!\mathfrak{C}_g$, one can write
$$\begin{aligned}
\big[(T\Phi)\star(T\Psi)\big](g)&=\sum_{h\in \textsf{G}}(T\Phi)(h)(T\Psi)(h^{-1}g) \\
&=\sum_{h\in \textsf{G}}\pi_h\left[P_h(\Phi)\right]\,\pi_{h^{-1}g}\big[P_{h^{-1}g}(\Psi)\big] \\
&\overset{\eqref{primika}}{=}\sum_{h\in \textsf{G}}\pi_g\big[P_h(\Phi)P_{h^{-1}g}(\Psi)\big]\\
&=\pi_g\Big(\sum_{h\in \textsf{G}}P_h(\Phi)P_{h^{-1}g}(\Psi)\Big)\\
&\overset{\eqref{multiplix}\text{\@ref(eq:multiplix)}}=\pi_g\big[P_g(\Phi\Psi)\big]=\big[T(\Phi\Psi)\big](g)\,, 
\end{aligned}$$ showing that $T$ is an algebraic morphism. Finally we
treat the involution: $$\begin{aligned}
\left[T(\Phi)\right]^\star\!(g) & =\pi_{g^{-1}}\!\left[P_{g^{-1}}(\Phi)\right]^*\overset{\eqref{secundika}}{=} \pi_g\big[P_{g^{-1}}(\Phi)^*\big]\\
& \overset{\eqref{multiplix}}{=} \pi_g[P_g(\Phi^*)]= \big[T(\Phi^*)\big](g)\,.
\end{aligned}$$
:::

With Proposition \@ref(prp:isometrix) in hand, we prove now our main abstract result.
Recall that a Banach $^*$-algebra is called *reduced* if its universal
$C^*$-seminorm is in fact a norm. In this case, its enveloping
$C^*$-algebra is simply its completion in this $C^*$-norm (no quotient
is needed).

::: {.theorem #teoremix} 
Let $\mathfrak C=\widetilde{\bigoplus}_{g\in{\textsf{G}}}\mathfrak C_g$
be topologically graded over a rigidly symmetric discrete group
${\textsf{G}}$ .

(i).  $\ell^1(\mathfrak C)$ is a symmetric Banach $^*$-algebra.

(ii).  $\ell^1(\mathfrak C)$ is an inverse closed subalgebra of
    $\,\mathfrak C$ .

(iii).  Let $\Pi:\mathfrak C\to \mathbb{B}(\mathcal{H})$ be a faithful
    representation. Then $\Pi\left[\ell^1(\mathfrak C)\right]$ is
    inverse closed in $\mathbb{B}(\mathcal{H})$ .
:::

::: proof
(i). By [@Pa2 Th.11.4.2], a closed $^*$-algebra of a symmetric
Banach $^*$-algebra is also symmetric. Proposition
\@ref(prp:isometrix)
and the fact that $\ell^1(\textsf{G};\mathcal B)$ was assumed symmetric proves
the result.

(ii). It is known [@Pa2 11.4] that a reduced Banach $^*$-algebra is
symmetric if and only if it is inverse closed in its enveloping
$C^*$-algebra. If we show that we are in such a case, we then apply (i).
Our $\ell^1(\mathfrak C)$ is clearly reduced, being given as a
$^*$-subalgebra of $\mathfrak C$ . Actually, we claim that $\mathfrak C$
can be seen as (a copy of) the enveloping $C^*$-algebra of
$\ell^1(\mathfrak C)$ . In [@SW Corol. 4.8] it is shown that a symmetric
group (as our rigidly symmetric $\textsf{G}$) is surely amenable. For such
groups, one may identify $\mathfrak C$ with both the full and the
reduced $C^*$-algebras of the Fell bundle associated to the topological
grading [@Ex3 Prop. 4.2 ,Thm. 4.7] and then the assertion about
enveloping follows [@FD2 VIII.17].

(iii). Is a consequence of (ii), since any $C^*$-algebra is inverse
closed in a larger $C^*$-algebra.
:::

In the context of group actions on $C^*$-algebras one deals with
convolution dominated kernels and operators [@FL; @FGL; @Gr; @GL2; @Ma].
We briefly indicate an extension for the topologically graded case,
leading to another form of a symmetric Banach $^*$-algebra at the level
of kernels. Representations by integral operators and their inverse
closedness properties are left to the reader.

::: {.definition #kimpembe}
*A convolution dominated kernel* (or *matrix*) is a function
$K:{\textsf{G}}\times\textsf{G}\to \mathfrak{C}$ such that
$K(g,h)\in\mathfrak{C}_{gh^{-1}}$ for every $g,h\in{\textsf{G}}$ and
such that the norm $$\label{cambio}
\,\big\Vert\,\!K\!\,\big\Vert\,_\mathscr{K}\,:=\inf\big\{\!\,\big\Vert\,\!\kappa\!\,\big\Vert\,_{\ell^1({\textsf{G}})}\,\big\vert\,\,\big\Vert\,\!K(g,h)\!\,\big\Vert\,_\mathfrak{C}\,\le|\kappa(gh^{-1})|\,,\,\forall\,g,h\in{\textsf{G}}\big\}$$
is finite. We denote by $\mathscr K_{{\textsf{G}}}(\mathfrak{C})$ the
vector space of all these convolution dominated kernels. An element $K$
of $\mathscr K_{{\textsf{G}}}(\mathfrak{C})$ is called *covariant*,
and we write
$K\in\mathscr{K}^{\textrm{ co}}_{{\textsf{G}}}(\mathfrak{C})$ , if
$$\label{pusimic}
K(gk,hk)=K(g,h)\,,\quad\forall\,g,h,k\in{{\textsf{G}}}\,.$$
:::

From the definition above, $K$ is covariant if and only if for all
$g,h\in G$ we have $K(g, h)= k_0(gh^{-1})$ for some function
$k_0:G\rightarrow \mathfrak{C}$ such that $k_0(k)\in \mathfrak{C}_k$ for
all $g\in G$ and $\| k_0(\cdot ) \|_{\mathfrak C}\in \ell^1(G)$. Thus
the isomorphism between $\mathscr K^{\textrm{ co}}_\textsf{G}(\mathfrak C)$ and
$\ell^1(\mathfrak C)$ is straightforward.

It is straightforward to show that endowed with the norm
$\Vert\!\cdot\!\Vert_\mathscr K$ , the multiplication $$\label{greta}
(K\bullet L)(g,h):=\sum_{k\in\textsf{G}}K(g,k)L(k,h)$$ and the involution
$K^\bullet(g,h):=K(h,g)^*$, the space
$\mathscr K_{{\textsf{G}}}(\mathfrak C)$ is a Banch $^*$-algebra.

::: {.corollary #climatic}
The subspace $\mathscr K^{\textrm{ co}}_{{\textsf{G}}}(\mathfrak C)$ is a
symmetric Banach $^*$-algebra.
:::

::: proof
It is easy to check that $\mathscr K^{\textrm{ co}}_\textsf{G}(\mathfrak C)$ is a closed $^*$-subalgebra
of $\mathscr K_\textsf{G}(\mathfrak C)$ . Let us define 
\begin{equation}
\big[\Upsilon(\Phi)\big](g,h):=\widetilde P_{gh^{-1}}(\Phi)\,,\quad\forall\,g,h\in\textsf{G}\,. (\#eq:london)
\end{equation}
Then $\Upsilon:\ell^1(\mathfrak C)\to\mathscr K_\textsf{G}(\mathfrak C)$ is an isometric $^*$-morphism with range $\mathscr K^{\textrm{ co}}_\textsf{G}(\mathfrak C)$. For the algebraic
relations use \@ref(eq:multiplix) and \@ref(eq:multiplex) (extended). On this range, the inverse reads
\begin{equation}
\big[\Upsilon^{-1}(K)\big]_g:=K(g,\textsf{e})\,,\quad\forall\,g\in\textsf{G}\,. (\#eq:reads)
\end{equation}
Since
$\mathscr K^{\textrm{ co}}_\textsf{G}(\mathfrak C)$ and $\ell^1(\mathfrak C)$
are isomorphic, the result follows from Theorem \@ref(thm:teoremix) (i).
:::

::: {.conjecture #fratrix}
In [@Ra] it is shown how to deform Fell
bundles by a cohomological twisting. We adapt this here to our problem.
Let $\omega:{\textsf{G}}\!\times\!{\textsf{G}}\to\mathbb{T}$ be a $2$-cocycle,
bound to satisfy for every $g,h,k\in{\textsf{G}}$ the axioms
$$\label{bundix}
\omega(g,h)\omega(gh,k)=\omega(h,k)\omega(g,hk)\,,\quad\omega(g,\textsf{e})=1=\omega(\textsf{e},g)\,.$$ For a
topologically graded $C^*$-algebra
$\mathfrak C=\widetilde{\bigoplus}_{g\in{\textsf{G}}}\mathfrak C_g$ ,
it is possible to construct a new one $\mathfrak C\{\omega\}$ in the
following way: On the (same) algebraic direct sum we modify the
algebraic structure, setting for finite sums $\Phi:=\sum_g\!\Phi_g$ and
$\Psi:=\sum_g\!\Psi_g$ $$\label{finitex}
\Phi\cdot_\omega\!\Psi:=\sum_{g,h}\omega(g,h)\Phi_g\Psi_h\,,\quad\Phi^{*_\omega}\!:=\sum_g\overline{\omega(g,g^{-1})}\Phi_g\,.$$

An argument using Fell bundles and the amenability of our discrete group
certifies the existence of the topological graded $C^*$-algebra
$\mathfrak C\{\omega\}=\widetilde{\bigoplus}^\omega_{g\in{\textsf{G}}}\mathfrak C_g$ .
The norm is also different (on the common algebraic sum), having in view
the way the universal norm (identical here with the reduced one, by
amenability) is constructed in the setting of Fell bundles. *In the case
where $\omega$ is not trivially equal to $1$, the Banach $^*$-algebra
$\ell^1\big(\mathfrak C\{\omega\}\big)$ is different from
$\ell^1(\mathfrak C)$ and it is symmetric and inverse closed in
$\mathfrak C\{\omega\}$.*
:::

## Topologically graded algebras from dual actions and partial crossed products {#cerculix}

Given a $C^*$-algebra, it is often not obvious whether it has an
interesting grading or not. In this subsection we are going to review
some ways to solve this problem, following especially results of Exel,
Quigg and Raeburn. This will lead to two reformulations of Theorem \@ref(thm:theoremix) that can be useful when studying examples and which will also provide
the reader with a more extended picture. We will take advantage of the
fact that our group $\textsf{G}$ is discrete and amenable; this will allow for
some simplifications.

The most general statement is that in this setting, *topologically
graded $C^*$-algebras over $\textsf{G}$ are equivalent to coactions of $\,\textsf{G}$* ,
cf. [@Qu] and [@Ra App. A]. In this direction we only indicate the case
of Abelian groups and the dual of an Abelian group is a group, making
the constructions more transparent.

So we fix for a while a discrete Abelian group $\textsf{G}$ . Its Pontryagin
dual $\widehat{\textsf{G}}$ is a compact Abelian group with normalized Haar
measure $d\chi$ . Let $\big(\mathfrak C,\alpha,\widehat{G}\,\big)$ be a (usual,
full) action of $\widehat{G}$ on a $C^*$-algebra. For every $g\in\textsf{G}$ let
\begin{equation}
\mathfrak C_g:=\big\{\Phi\in\mathfrak C\,\big\vert\,\alpha_\chi(\Phi)=\chi(g)\Phi\,,\,\forall\,\chi\in\widehat{G}\big\} (\#eq:spectrix)
\end{equation}
be the $g$'th spectral subspace of the action. It is easy to see that
one gets a grading, as in (\@ref(eq:veverita)).
We have now the concrete projections 
\begin{equation}
\widetilde P_g:\mathfrak C\to\mathfrak C_g\,,\quad \widetilde P_g(\Phi):=\int_{\widehat{G}}\,\overline{\chi(g)}\,\alpha_\chi(\Phi)\,d\chi\,, (\#eq:projetrix)
\end{equation}
which are obviously contractive; then $\mathfrak C$ is a topological
grading. We can reformulate Theorem
\@ref(thm:teoremix) in
this Abelian setting; the $\ell^1$-algebra will deserve a special
notation, to recall the action $\alpha$ and the type of decay.

::: {.theorem #exelix}
Let $\big(\mathfrak C,\alpha,{\widehat{G}}\,\big)$ be a continuous action
of a compact Abelian group ${\widehat{G}}$ on a unital $C^*$-algebra.
Denoting by ${\textsf{G}}$ the dual of $\,{\widehat{G}}$ ,
\begin{equation}
\ell^1(\mathfrak C)\equiv\bigoplus_{g\in{\textsf{G}}}^{1,\alpha}\mathfrak C_g=\Big\{\Phi\in\mathfrak C\;\Big\vert\,\sum_{g\in{\textsf{G}}}\,\big\Vert\,\! \widetilde P_g(\Phi)\!\,\big\Vert\,\,<\infty\Big\} (\#eq:peru)
\end{equation}
is a reduced and symmetric Banach $^*$-algebra, which is inverse closed
in $\mathfrak C$ .
:::

:::{.conjecture #crucix}
Using normal subgroups of ${\textsf{G}}$
one can increase the family of symmetric subalgebras. If, as above,
$\big(\mathfrak C,\alpha,\widehat{{\textsf{G}}}\,\big)$ is a
continuous action of the dual of the Abelian discrete group
${\textsf{G}}$ and $\textsf{N}$ is a normal subgroup, the dual
$\widehat{{\textsf{G}}/\textsf{N}}$ of the quotient is isomorphic to the
closed subgroup 
\begin{equation}
\textrm{ Ann}\big(\textsf{N}\!\mid\!\widehat{G}\big):=\big\{\chi\in\widehat{G}\,\big\vert\,\chi|_{\textsf{N}}=1\big\}\,. (\#eq:clarix)
\end{equation}
Thus from $\alpha$ we deduce a continuous action $\alpha^\textsf{N}$ of
$\widehat{{\textsf{G}}/\textsf{N}}$ on $\mathfrak C$ , first by restricting
$\alpha$ to $\textrm{ Ann}\big(\textsf{N}\!\mid\!\widehat{G}\big)$ and then composing
with the isomorphism. In this way we obtain the new symmetric Banach
$^*$-algebra 
\begin{equation}
\ell^1\big(\mathfrak{C}^{{\textsf{G}}/\textsf{N}}\big)\equiv\bigoplus_{\gamma\in{\textsf{G}}/\textsf{N}}^{1,\alpha^{\textsf{N}}}\mathfrak{C}_{\gamma}\,.
%=\Big\{\Phi\in\mathfrak C\;\Big\vert\,\sum_{g\in{\textsf{G}}}\,\big\Vert\,\! \widehat P_g(\Phi)\!\,\big\Vert\,\,<\infty\Big\} (\#eq:perux)
\end{equation}
Extreme cases are
$\ell^1\big(\mathfrak C^{{\textsf{G}}/\{\textsf{e}\}}\big)=\ell^1(\mathfrak C)$
and
$\ell^1\big(\mathfrak C^{{\textsf{G}}/{\textsf{G}}}\big)=\mathfrak C$.
:::

Crossed products assigned to partial actions of (discrete) groups $\textsf{G}$
on (unital) $C^*$-algebras are among the most important examples of
graded $C^*$-algebras, and they were our initial motivation. In [@Ex2
Thm. 27.11] they are characterized among the larger class, while [@QR
Thm. 4.1] gives a Landstad-type description of them in terms of the
associated coaction. In many cases what we are actually given is the
partial action; the grading comes afterwards. Now the discrete group
$\textsf{G}$ is no longer Abelian.

::: {.definition #bazika}
A *partial action* of ${\textsf{G}}$ on
the $C^*$-algebra $\mathcal{A}$ is a pair
$\big(\{\mathcal{A}_g\}_{g\in {\textsf{G}}},\{\theta_g\}_{g\in{\textsf{G}}}\}\big)$ ,
where for each $g\in {\textsf{G}}$ , $\mathcal{A}_g$ is a closed two-sided
ideal in $\mathcal{A}$ , $\theta_g$ is a $^*$-isomorphism from $\mathcal{A}_{g^{-1}}$ onto
$\mathcal{A}_g$, satisfying the following conditions, for all
$g,h\in{\textsf{G}}$ :

1.  $\mathcal{A}_\textsf{e}=\mathcal{A}$ and $\theta_\textsf{e}$ is the identity automorphism of $\mathcal{A}$ ,

2.  $\theta_g\!\left(\mathcal{A}_{g^{-1}}\!\cap \mathcal{A}_h\right)\subset\mathcal{A}_{gh}$ ,

3.  $\theta_g\big(\theta_h(a)\big)=\theta_{gh}(a)$ ,
    $\forall\,a\in\mathcal{A}_{h^{-1}}\!\cap\mathcal{A}_{(gh)^{-1}}$ .
:::

We also denote by $(\mathcal{A},\theta,\textsf{G})$ the partial dynamical system. It follows
easily that we have $\theta_{g^{-1}}\!=\theta_g^{-1}$. Our main object is the
following vector space: 
\begin{equation}
\ell^1_\theta(\textsf{G};\mathcal{A}):= \left\{\Phi\in\ell^1(\textsf{G};\mathcal{A})\mid\Phi(g)\in \mathcal{A}_g \,,\,\forall\,g\in \textsf{G}\right\}, (eq:thetika)
\end{equation}
which is obviously closed. For $\Phi,\Psi\in\ell^1_\theta(\textsf{G};\mathcal{A})$ we define
the product 
\begin{equation}
\left( \Phi\star_{\theta} \Psi\right)(g)  =\sum_{h\in \textsf{G}} \theta_h\!\left[\theta_{h}^{-1}\big(\Phi(h)\big)\Psi\big(h^{-1}g\big)\right] (eq:strugure)
\end{equation}
and the involution
$\Phi^{\star_\theta}(g) = \theta_g\!\left[\Phi\big(g^{-1}\big)\right]^*.$
Then
$\big(\ell^1_\theta(\textsf{G};\mathcal{A}),\star_{\theta},^{\star_{\theta}}\!,\|\cdot\|_{\ell^1_\theta(\textsf{G};\mathcal{A})}\big)$
is a Banach $^*$-algebra. We will refer to it as *the $\ell^1$-partial
crossed product*. Its enveloping $C^*$-algebra is denoted by
$\mathcal{A}\!\rightthreetimes_\theta\!\textsf{G}$ and called *the partial crossed product associated to
$(\mathcal{A},\theta,\textsf{G})$* . We used the fancy symbol $\rightthreetimes$ instead of the more
usual $\rtimes$ to stress that our crossed product is assigned to a
*partial* action.

We indicate the particularization of Theorem \@ref(thm:teoremix) to
partial actions. Since $\textsf{G}$ must be amenable, by [@Ex3] the full and the
reduced partial crossed products are identical and possess a (faithful)
positive contractive conditional expectation.

::: {.theorem #corolyx}
Let $(\mathcal{A},\theta,{\textsf{G}})$ be a partial
$C^*$-dynamical system with rigidly symmetric discrete group
${\textsf{G}}$ and unital $C^*$-algebra $\mathcal{A}$. Then
$\ell^1_\theta({\textsf{G}};\mathcal{A})$ is symmetric and inverse closed in
$\mathcal{A}\rightthreetimes_\theta\!{\textsf{G}}$. If
$\,\Pi:\mathcal{A}\rightthreetimes_{\theta}\!{\textsf{G}}\to \mathbb{B}(\mathcal{H})$ is a faithful
representation, $\Pi\left[\ell^1_\theta({\textsf{G}};\mathcal{A})\right]$ is
inverse closed in $\mathbb{B}(\mathcal{H})$.
:::

::: proof
The crossed product $\mathfrak C:=\mathcal{A}\!\rightthreetimes_\theta\!\textsf{G}$ is a
topologically graded $C^*$-algebra [@Ex2], where 
\begin{equation}
\mathfrak C_g=\big\{\Phi\in\ell^1_\theta(\textsf{ G};\mathcal{A})\,\big\vert\,\textrm{ supp}(\Phi)\subset\{g\}\big\}\,,\quad\forall\,g\in\textsf{G}\,. (eq:verita)
\end{equation}
Its $\ell^1$-algebra is 
\begin{equation}
\ell^1(\mathfrak C)\equiv\ell^1\big(\mathcal{A}\!\rightthreetimes_\theta\!\textsf{G}\big)=\ell^1_\theta(\textsf{G};\mathcal{A})\,, (eq:veveriz)
\end{equation}
reinterpreting $\rightthreetimes_\theta$ as the partial crossed product between group
$G$ and the $C^*$-algebra $A$. Thus we can apply Theorem
\@ref(thm:teoremix).
:::

:::{.conjecture #apucalaie}
The result can also be obtained
directly, by means specific to partial action. To prove the isometric
linear embedding
$\ell^1_\theta(\textsf{ G};\mathcal{A})\hookrightarrow\ell^1\big(\textsf{G};\mathbb B(\mathcal{H}))$
one uses the map $\big[T(\Phi)\big](g):=\rho\big[\Phi(g)\big]u_g$ ,
where $(\rho,u)$ is a covariant representation of $(\mathcal{A},\theta,\textsf{G})$ in the
Hilbert space $\mathcal{H}$ , as in [@Ex2 Sect. 13]. Here $\rho$ should be a
*faithful* representation of $\mathcal{A}$ and $u$ a *partial* representation of
$\textsf{G}$, connected by an equivariance condition.
:::

## Inverse closedness modulo ideals. {#idealuri}

::: {.definition #idealix}
Let $\mathfrak{K}$ be an ideal of the
unital C$^*$-algebra $\mathfrak{C}$ . The $^*$-subalgebra $\mathfrak{B}$
of $\mathfrak{C}$ is called *$\mathfrak{K}$-inverse closed* if
$\mathfrak{B}/(\mathfrak{B}\cap\mathfrak{K})$ is inverse closed in
$\mathfrak{C}/\mathfrak{K}$.
:::

::: {.example #fredholmix}
If $\mathfrak{K}=\{0\}$, the notion coincides with that introduced in Definition (\@ref(def:symmetric)).
However the main motivating case is as follows: Let $\mathfrak C$ be a
$C^*$-algebra of bounded operators in the Hilbert space $\mathcal{H}$ ,
containing the ideal $\mathbb K(\mathcal{H})$ of all the compact operators. We
recall that $T\in\mathbb B(\mathcal{H})$ is called *Fredholm* if its range is
closed and its kernel and its cokernel are both finite-dimensional. By
Atkinson's Theorem, this happens exactly if the image of $T$ in the
Calkin algebra $\mathbb B(\mathcal{H})/\mathbb K(\mathcal{H})$ is invertible. A
$^*$-subalgebra $\mathfrak B$ of $\mathbb B(\mathcal{H})$ will be called
*Fredholm inverse closed* if the situation in Definition (\@ref(def:idealix)) holds
with $\mathfrak K=\mathbb K(\mathcal{H})$ . For $\mathfrak C$ we can take any
$C^*$-algebra of $\mathbb B(\mathcal{H})$ containing $\mathfrak B$.
:::

::: {.definition #buhonero} 
Let $\mathfrak C=\widetilde{\bigoplus}_{g\in{\textsf{G}}}\mathfrak C_g$
be a graded $C^*$-algebra over the discrete group $\textsf{G}$ . The ideal
$\mathfrak K$ of $\mathfrak C$ is *a graded ideal* if the ideal
generated by $\mathfrak K\cap\mathfrak C_\textsf{e}$ coincides with
$\mathfrak K$ (or, equivalently, that
$\bigoplus_{g\in{\textsf{G}}}\mathfrak K\cap\mathfrak C_g$ is dense
in $\mathfrak K$).
:::

::: {.theorem #ruye} 
Let $\mathfrak C=\widetilde{\bigoplus}_{g\in{\textsf{G}}}\mathfrak C_g$
be a topologically graded $C^*$-algebra over the discrete rigidly
symmetric group ${\textsf{G}}$ and $\mathfrak K$ a graded ideal. Then
$\ell^1(\mathfrak C)$ is $\mathfrak K$-inverse closed in $\mathfrak C$ .
:::

::: proof
One needs to show that
$\ell^1(\mathfrak C)/\ell^1(\mathfrak C)\cap\mathfrak K$ is inverse
closed in $\mathfrak C/\mathfrak K$ . Let us denote by
$\kappa:\mathfrak C\to\mathfrak C/\mathfrak K$ the quotient map. By
[@Ex2 Prop. 23.10] (or by [@Ex3 Prop. 3.11]), under the stated
conditions upon the graded algebra and the ideal,
$\mathfrak C/\mathfrak K$ is topologically graded by the subspaces
$$\big\{(\mathfrak C/\mathfrak K)_g:=\kappa(\mathfrak C_g)\,\big\vert\,g\in\textsf{G}\big\}\,.$$
The corresponding linear contraction
$\widetilde Q_g:\mathfrak C/\mathfrak K\to(\mathfrak C/\mathfrak K)_g$
satisfies $$\label{traznau}
\widetilde Q_g\circ\kappa=\kappa\circ\widetilde P_g\,,\quad\forall\,g\in\textsf{G}\,.$$
Using this and the form of the $\ell^1$-norms, one shows immediately
that $\kappa$ sends $\ell^1(\mathfrak C)$ into
$\ell^1(\mathfrak C/\mathfrak K)$ contractively. Its kernel is clearly
$\ell^1(\mathfrak C)\cap\mathfrak K$ . Let us show its surjectivity,
starting from
$$\varphi:=\sum_{g\in\textsf{G}}\varphi_g\equiv\sum_{g\in\textsf{G}}\widetilde Q_g(\varphi)\in\ell^1(\mathfrak C/\mathfrak K)$$
(unconditional convergence in $\mathfrak C/\mathfrak K$) . Let
$\{\beta_g\!\mid\!g\in\textsf{G}\}$ be a summable family of positive numbers.
For each $g$, there is an element $\Phi_g\in\mathfrak C_g$ such that
$\kappa(\Phi_g)=\varphi_g$ and
$\Vert\!\Phi_g\!\Vert_\mathfrak C\,\le\,\Vert\!\varphi_g\!\Vert_{\mathfrak C/\mathfrak K}+\beta_g$ .
Then $\Phi:=\sum_{g}\Phi_g\in\ell^1(\mathfrak C)$ and
$\kappa(\Phi)=\varphi$ . So
$\ell^1(\mathfrak C)/\ell^1(\mathfrak C)\cap\mathfrak K$ may be
identified with $\ell^1(\mathfrak C/\mathfrak K)$ . We apply Theorem
\@ref(thm:teoremix)
(ii) to the topologically graded quotient algebra
$\mathfrak C/\mathfrak K$ and finish the proof. ◻
:::

The particular case of partial actions is worth mentioning. Suppose that
$(\mathcal{A},\theta,\textsf{G})$ is a partial dynamical system with discrete
group $\textsf{G}$ and that $\mathcal{K}$ is an ideal of $\mathcal{A}$ that is
$\theta$-invariant:
$$\theta_g\big(\mathcal{A}_{g^{-1}}\!\cap\mathcal{K}\big)\subset \mathcal{K}\,,\quad\forall\,g\in \textsf{G}\,.$$
We denote by the same letter $\theta$ the action of $\textsf{G}$ by partial
automorphisms of $\mathcal{K}$ defined by restrictions. One gets the
C$^*$-partial dynamical system $(\mathcal{K},\theta,\textsf{G})$ . The partial
crossed product $\mathcal{K}\rightthreetimes_{\theta}\textsf{G}$ may be identified with an
ideal of $\mathcal{A}\rightthreetimes_{\theta}\textsf{G}$ . Under this identification,
$\ell^1_{\theta}(\textsf{G};\mathcal{K})$ becomes an ideal of
$\ell^1_{\theta}(\textsf{G};\mathcal{A})$ in the natural way: the
$\ell^1$-function $\varphi:\textsf{G}\rightarrow \mathcal{K}$ is taken to be
$\mathcal{A}$-valued. One can use the exactness of the partial crossed
product construction [@ELQ Sect. 3] to prove

::: {.theorem #theoremix}
Assume that the discrete group ${\textsf{G}}$ is rigidly symmetric. The Banach $^*$-algebra
$\ell^1_{\theta}({\textsf{G}};\mathcal{A})$ is
$\mathcal{K}\!\rightthreetimes_{\theta}\!{\textsf{G}}$-inverse closed in the
partial crossed product $\mathcal{A}\!\rightthreetimes_{\theta}\!{\textsf{G}}$
for any $\theta$-invariant ideal $\mathcal{K}$ of $\mathcal{A}$ .
:::

Theorem (\@(thm:theoremix)) can also be obtained as a consequence of Theorem (\@(thm:ruye)), since partial
crossed products are topologically graded, and the ideal
$\mathcal{K}\!\rightthreetimes_{\theta}\!\textsf{G}$ is indeed graded under the stated
assumptions.

The situation in Example (\@ref(exm:fredholmix)) is the most interesting:

::: {.corollary #honduras} 
Let $(\mathcal{A},\theta,{\textsf{G}})$ be a
partial C$^*\!$-dynamical system with discrete rigidly symmetric group
${\textsf{G}}$ and $\mathcal{K}$ a $\theta$-invariant ideal in $\mathcal{A}$ . Let
$\Pi\!:\!\mathcal{A}\rightthreetimes_{\theta}\!{\textsf{G}} \to \mathbb{B}(\mathcal{H})$
be a faithful representation such that
$\Pi\big(\mathcal{K}\rightthreetimes_{\theta}\!{\textsf{G}}\big)=\mathbb{K}(\mathcal{H})$ .
Then the Banach $^*$-algebra $\Pi[\ell^1_{\theta}({\textsf{G}};\mathcal{A})]$
is Fredholm inverse closed.
:::

## Other types of decay {#decay}

::: {.definition #sconx} A *weight* on the discrete group
${\textsf{G}}$ is a function $\nu: {\textsf{G}}\to [1,\infty)$
satisfying everywhere $$\label{submultiplicative}
 \nu(gh)\leq \nu(g)\nu(h)\,,\quad\nu(g^{-1})=\nu(g)\,, \quad \forall g,h\in{\textsf{G}}.$$
Let $\mathfrak C$ be a topologically graded $C^*$-algebra. On
$\,\bigoplus_{g\in{\textsf{G}}}\!\mathfrak C_g$ we can introduce the
norm 
\begin{equation}
\,\big\Vert\,\!\Phi\!\,\big\Vert\,_{\ell^{1,\nu}(\mathfrak C)}\,:=\sum_{g\in{\textsf{G}}}\nu(g)\!\,\big\Vert\,\!P_g(\Phi)\!\,\big\Vert\,. (\#eq:normix)
\end{equation}
The completion in this norm, denoted by $\ell^{1,\nu}(\mathfrak C)$ ,
can be seen as a Banach $^*$-algebra with the algebraic structure
inherited from $\ell^1(\mathfrak C)$ (or from $\mathfrak C$) .
:::

::: {.theorem #oix}
Let ${\textsf{G}}$ be a rigidly symmetric
discrete group and $\nu$ a weight. Assume that there exists a generating
subset $V$ of $\,{\textsf{G}}$ containing the unit $\textsf{e}$ such that

1.  the following uGRS (uniform Gelfand-Raikov-Shilov) condition holds:
    \begin{equation}
    \lim_{n\rightarrow \infty}\sup_{g_1,\dots,g_n \in V}\nu(g_1\cdots g_n)^{\frac{1}{n}}=1\,, (\#eq:limitConditionOfWeight)
    \end{equation}

2.  for some finite constant $C$ one has for any $n\in\mathbb{N}$
    \begin{equation}
    \sup_{g\in V^n\setminus V^{n-1}}\nu(g) \leq C\!\inf_{g\in V^n\setminus V^{n-1}}\nu(g)\,.(\#eq:limitt)
    \end{equation}

Then $\ell^{1,\nu}(\mathfrak C)$ is a symmetric Banach $^*$-algebra for every topologically ${\textsf{G}}$-graded $C^*$-algebra $\mathfrak C$.
:::

::: proof
The problem of the symmetry of a weighted $\ell^1$-algebra as a
$^*$-subalgebra of an unweighted one has been solved in [@FGL Th.3] in
a more particular context. We are going to check that the arguments can
be adapted to the more general case. The main idea is proving that,
given an element $\Phi\in \ell^{1,\nu}(\mathfrak C)$ , its spectral
radius is the same as in $\ell^{1}(\mathfrak C)$ . Then one applies
Hulanicki's Lemma.

As $\nu(\cdot)\geq 1$ , we have
\begin{equation*}
\,\big\Vert\,\!\Phi\!\,\big\Vert\,_{\ell^{1}(\mathfrak C)}=\sum_{g\in{\textsf{G}}}\!\,\big\Vert\,\!P_g(\Phi)\!\,\big\Vert\,\leq\sum_{g\in{\textsf{G}}}\nu(g)\!\,\big\Vert\,\!P_g(\Phi)\!\,\big\Vert\, = \,\big\Vert\,\!\Phi\!\,\big\Vert\,_{\ell^{1,\nu}(\mathfrak C)}\,
\end{equation*}
and using the spectral radius formula
\begin{equation*}
r_{\ell^{1}(\mathfrak{C})}(\Phi)\leq r_{\ell^{1,\nu}(\mathfrak{C})}(\Phi)\,,\quad\forall\,\Phi\in {\ell^{1,\nu}(\mathfrak{C})}\,.
\end{equation*}
To prove the opposite inequality, pick $V$ a generating set for $\textsf{G}$ and
define on $\mathbb Z$ the function
\begin{equation*}
v(n):=\sup_{g\in V^{|n|}} \nu(g)\,.
\end{equation*}
Due to the uGRS condition, it is a weight and one has the obvious associated weighted space
$\ell^{1,\nu}(\mathbb{Z})$. By induction, from the equation
(\@ref(eq:normix)) we get
\begin{equation*}
\,\big\Vert\,\!\Phi^n \!\,\big\Vert\,_{\ell^{1,\nu}(\mathfrak{C})}\,\leq \sum_{g_1\in\textsf{G}}\cdots\sum_{g_n\in\textsf{G}}\nu(g_1\dots g_n)\,\big\Vert\,\!P_{g_1}(\Phi) \!\,\big\Vert\,\cdots \!\,\big\Vert\,\!P_{g_n}(\Phi) \!\,\big\Vert\,.
\end{equation*}
Since $\textsf{G}=\bigsqcup_{m\in\mathbb N}(V^m\setminus V^{m-1})$ , where
$V^0=\emptyset$, we may split the sum accordingly. This yields
\begin{equation}
\,\big\Vert\,\!\Phi^n \!\,\big\Vert\,_{\ell^{1,\nu}(\mathfrak{C})}\,\leq\!\sum_{m_1,\dots,m_n=1}^{\infty}\sum_{V^{m_1}\setminus V^{m_1-1}}\cdots\sum_{V^{m_n}\setminus V^{m_n-1}} \nu(g_1\dots g_n)\,\big\Vert\, P_{g_1}(\Phi) \!\,\big\Vert\,\cdots \!\,\big\Vert\, P_{g_n}(\Phi) \!\,\big\Vert\,. (\#eq:shocarix)
\end{equation}
If $g_j\in V^{m_j}\setminus V^{m_j-1}$, then
$g_1\cdots g_n \in V^{m_1+\cdots +m_n}$ and so the weight is majorized
by
$$\nu(g_1\cdots g_n)\leq \sup_{h\in V^{m_1+\cdots +m_n}} \nu(h) =v(m_1+\cdots m_n)\,.$$
Set $b_m:=\sum_{g\in V^m\setminus V^{m-1}}\!\,\big\Vert\, P_g(\Phi) \!\,\big\Vert\,$ and
$b=(b_m)_{m\in\mathbb N}$ . Then we have
$\!\,\big\Vert\,\Phi \!\,\big\Vert\,_{\ell^1(\mathfrak C)}\,=\,\,\big\Vert\, b \!\,\big\Vert\,_{\ell^1(\mathbb N)}$ .
Also the condition (\@ref(eq:limitt)) implies immediately that
$$C^{-1}\!\,\big\Vert\, b\!\,\big\Vert\,_{\ell^{1,v}(\mathbb Z)}\,\leq \,\,\big\Vert\,\Phi \!\,\big\Vert\,_{\ell^{1,\nu}(\mathfrak C)}\,\leq\,\,\big\Vert\,\,b \!\,\big\Vert\,_{\ell^{1,v}(\mathbb Z)}.$$
Returning to (\@ref(eq:shocarix)) we obtain
$$\!\,\big\Vert\, \Phi^n \!\,\big\Vert\,_{\ell^{1,\nu}(\mathfrak{C})}\,\leq\!\sum_{m_1,\dots,m_n=1}^{\infty}\!v(m_1+\cdots +m_n)\,b_{m_1}\cdots b_{m_n}\!=\;\,\big\Vert\, b^n \!\,\big\Vert\,_{\ell^{1,v}(\mathbb Z)}\,<\infty\,.$$
By its definition the weight $v$ on $\mathbb Z$ satisfies the
GRS-condition, and $\ell^{1,v}(\mathbb Z)$ is symmetric by [@FGL0].
Hence $$\begin{aligned}
r_{\ell^{1,\nu}(\mathfrak{C})}(\Phi)&=\lim_{n\rightarrow\infty} \!\,\big\Vert\, \Phi^n \!\,\big\Vert\,_{\ell^{1,\nu}(\mathfrak{C})}^{1/n}\leq \lim_{n\rightarrow\infty} \!\,\big\Vert\, b^n \!\,\big\Vert\,_{\ell^{1,\nu}(\mathbb{Z})}^{1/n}\\
&=r_{\ell^{1,\nu}(\mathbb{Z})}(b)=r_{\ell^{1}(\mathbb{Z})}(b)\\
&\le\,\,\big\Vert\, b \!\,\big\Vert\,_{\ell^{1}(\mathbb{Z})}=\,\,\big\Vert\, \Phi \!\,\big\Vert\,_{\ell^{1}(\mathfrak{C})}.
\end{aligned}$$ So for all $k\in\mathbb N$ we have
$$r_{\ell^{1,\nu}(\mathfrak{C})}(\Phi)=r_{\ell^{1,\nu}(\mathfrak{C})}(\Phi^n)^{1/n}\leq\,\,\big\Vert\, \Phi^n \!\,\big\Vert\,_{\ell^{1}(\mathfrak{C})}^{1/n},$$
and by letting $n\rightarrow\infty$ we obtain the required inequality
$\,r_{\ell^{1,\nu}(\mathfrak{C})}(\Phi)\leq r_{\ell^{1}(\mathfrak{C})}(\Phi)$ . ◻
:::

:::{.conjecture #labix}
There is a different way to prove Theorem (\@ref(thm:oix)). We define *the
Beurling algebra associated to the weight $\nu$ and to the $C^*$-algebra
$\mathcal B$* as $$\label{sharpix}
\ell^{1,\nu}({\textsf{G}};\mathcal B):=\big\{\Psi\, \vert \,\nu\Psi\in \ell^{1}({\textsf{G}};\mathcal B)\big\}\,,$$
with norm
$\Vert \cdot \!\Vert_{\ell^{1,\nu}({\textsf{G}},\mathcal B)}\,:=\,\Vert\nu\,\cdot\,\!\Vert_{\ell^{1}({\textsf{G}};\mathcal B)}$.
By [@FGL], the assumptions on the weight imply that
$\ell^{1,\nu}({\textsf{G}};\mathcal B)$ is a symmetric Banach
$^*$-algebra. One then shows as in Proposition \@ref(prp:isometrix)
an isometric embedding
$\ell^{1,\nu}(\mathfrak C)\hookrightarrow\ell^{1,\nu}({\textsf{G}};\mathcal B)$ ,
for some $C^*$-algebra $\mathcal B$ , and use this as in Theorem
\@ref(thm:teoremix) to
deduce the symmetry of $\ell^{1,\nu}(\mathfrak C)$ .
:::
